baseURL = 'http://mightier.news/'
languageCode = 'en-us'
title = 'Mightier News'
theme = "newsplit"

[params]
    showCenterTitleAndImage = true #disable the center title and logo image
    mainTitle = "You are paid as judge of future news(Coming Soon...)"
    mainImage = "images/logo_mn.svg"
    leftTitle = "ğŸ‘"
    leftSubTitle = "Media is broken, but we can build up together, right?"
    leftJpg = "images/debate.png"
    leftButtonText = "I value it"
    leftLink = "#"
    rightTitle = "ğŸ‘"
    rightSubTitle = "You will become a mighty guardian of truth, will you?"
    rightJpg = "images/zombies.png"
    rightButtonText = "I doubt it"
    rightLink = "#"