baseURL = 'http://mightier.news/'
languageCode = 'en-us'
title = 'You Are Mightier'
theme = "newsplit"

[params]
    showCenterTitleAndImage = true #disable the center title and logo image
    mainTitle = "You are paid to co-create future news(Coming Soon...)"
    mainImage = "images/logo_mn.svg"
    leftTitle = "ğŸ‘"
    leftSubTitle = "Do you want to give 2 cents to valuable content?"
    leftJpg = "images/debate.png"
    leftButtonText = "I value it"
    leftLink = "#"
    rightTitle = "ğŸ‘"
    rightSubTitle = "Do you want to pay 2 cents to defend the truth?"
    rightJpg = "images/zombies.png"
    rightButtonText = "I doubt it"
    rightLink = "#"