baseURL = 'http://here.news/'
languageCode = 'en-us'
title = "Here's the news"
theme = "newsplit"

[params]
    showCenterTitleAndImage = true #disable the center title and logo image
    mainTitle = "Future news is here(Coming Soon...)"
    mainImage = "images/logo_mn.svg"
    leftTitle = "ğŸ‘"
    leftSubTitle = "Give 2 cents to valuable content?"
    leftJpg = "images/debate.png"
    leftButtonText = "I value it"
    leftLink = "#"
    rightTitle = "ğŸ‘"
    rightSubTitle = "Pay 2 cents to defend the truth?"
    rightJpg = "images/zombies.png"
    rightButtonText = "I doubt it"
    rightLink = "#"